### ISSUE TITLE
The cmd argument should be wrapped in quotes

### ISSUE THREAD

**Issue by di** [GoogleCloudPlatform/functions-framework-conformance#48]
Using a configuration like:

```yaml
    - name: Run cloudevent conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v0.3.2
      with:
        functionType: 'cloudevent'
        useBuildpacks: false
        validateMapping: false
        cmd: "functions-framework --source tests/conformance/main.py --target write_cloud_event --signature-type cloudevent"
```

Produces:

```
Error: Command failed: client -output-file=function_output.json -type=http -validate-mapping=false -builder-source= -builder-target= -builder-runtime= -builder-tag=latest -buildpacks=false -cmd=functions-framework --source tests/conformance/main.py --target write_http --signature-type http -start-delay=1
flag provided but not defined: -source
```
